# Generated by Django 5.2.14 on 2026-05-19 22:09

from django.db import migrations, models


def copy_legacy_company_to_organization(apps, schema_editor):
    Registration = apps.get_model('registrations', 'Registration')
    for registration in Registration.objects.all().only('id', 'company', 'organization'):
        if not registration.organization and registration.company:
            registration.organization = registration.company
            registration.save(update_fields=['organization'])


def reverse_copy_legacy_company_to_organization(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='forum_direction',
            field=models.CharField(blank=True, choices=[('tech', 'Технологии и инновации'), ('social', 'Социальный бизнес'), ('business', 'Малый бизнес'), ('wellness', 'Красота и здоровье'), ('fashion', 'Мода'), ('craft', 'Мастера'), ('media', 'Медиа'), ('svo', 'СВОя волна (секция для участников СВО)')], default='', max_length=40, verbose_name='направление форума'),
        ),
        migrations.AddField(
            model_name='registration',
            name='forum_direction_label',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='название направления форума'),
        ),
        migrations.AddField(
            model_name='registration',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='учебное заведение / организация'),
        ),
        migrations.AddField(
            model_name='registration',
            name='study_or_position',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='направление обучения / должность'),
        ),
        migrations.AddField(
            model_name='registration',
            name='vk_url',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='ссылка ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='company',
            field=models.CharField(blank=True, max_length=180, verbose_name='компания / учебное заведение, старое поле'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='электронная почта, старое поле'),
        ),
        migrations.RunPython(copy_legacy_company_to_organization, reverse_copy_legacy_company_to_organization),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['vk_url'], name='registratio_vk_url_d581b3_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['forum_direction'], name='registratio_forum_d_eab55b_idx'),
        ),
    ]
